// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  gameType: __t.string().name("game_type"),
  status: __t.string(),
  isPublic: __t.bool().name("is_public"),
  isLocal: __t.bool().name("is_local"),
  hostIdentity: __t.identity().name("host_identity"),
  maxPlayers: __t.u32().name("max_players"),
  createdAt: __t.timestamp().name("created_at"),
  lastActivity: __t.timestamp().name("last_activity"),
});
